### ISSUE TITLE
Show empty state in more situations

### ISSUE THREAD

**Issue by buywetwok** [kaczmarkiewiczp/rcloneExplorer#113]
Been toying with the idea whether the empty state (the Ooops! screen) should be shown in more scenarios, not just when the rclone config file is not present.

Right now, the empty state is only shown when the user hasn't created a rclone config, either manually or through importing.

However, the user can also end up with a blank screen with no remotes shown, when the user manually deletes all existing remotes.

In #112 I've began a change where when there's no remotes left, the empty state can also be shown to the user. This way, when the user opens the app again, or try to list the remotes using the left navigation menu, they'll be shown the empty state.

I've also updated the message to prompt the user to either import config or just add a remote in through the app directly.

There is one other scenario that haven't been dealt with yet, which is when the user deletes their last remote, an empty list of remotes will be shown instead of auto-refreshing the view to display the empty state immediately. Tried a few things but I haven't been able to refresh the remote fragment after a delete remote event (and of course, the remotes list being empty). It feels like better user experience if the user can be taken to the empty state immediately.

**Comment by kaczmarkiewiczp** [comment]
While testing this I also discovered that if a new remote is added while the empty screen state is showing, the empty state won't go away until the fragment is relaunched again. I have an idea how to fix it.
