### ISSUE TITLE
add webdav serve and built-in images browser

### ISSUE THREAD

**Issue by xiaolei0125** [kaczmarkiewiczp/rcloneExplorer#177]
rcloneExplorer is a very cool project.

Can add rclone serve webdav function for rcloneExplorer, since many android app support webdav but not http? 

Can support a built-in image viewer in rcloneExplorer, browse pictures one by one without opening a third-party photo browser app for every time.

**Comment by kaczmarkiewiczp** [comment]
Those look like two different suggestions. Could you split this into two different issues? Thanks.

**Comment by xiaolei0125** [comment]
@kaczmarkiewiczp  ok, thanks,   I closed this issue, and add two new issue.
