### ISSUE TITLE
how to stream?

### ISSUE THREAD

**Issue by caspertone2003** [kaczmarkiewiczp/rcloneExplorer#178]
Can you provide some insight of how should I configure rcloneExplorer to be able to stream?
I have an Android box so really do not know to how to do it.
I see in the app create link and serve http none of them help me with vlc in android - I see only video, audio, local network.... but I cannot include an http link anywhere...
(it would be much easier with a "share to" or alike ... probably it is there but I cannot get it....)

Thanks again

**Comment by caspertone2003** [comment]
I found how.
Just a short click on the file name... or selecting the vertical three dots close to the name clicking on open...

**Comment by kaczmarkiewiczp** [comment]
I'll answer this question in case anyone else has similar problems in the future. Single click on a file will open it. Videos and music will be streamed, while any other file will be downloaded to the device and then opened. For all non-crypt remotes, file type is determined using mime type returned by rclone. For crypt remotes that information is not available, and file type is determined using the file extension. It's also possible to force files to open as a certain type. Click on the file menu (the three dots next to the file), open as, and then select the type.
