### ISSUE TITLE
Improvement request : rclone sync

### ISSUE THREAD

**Issue by FoxP** [kaczmarkiewiczp/rcloneExplorer#181]
Hello,

Since we are now able to download / upload files, can you please add the `rclone sync` command to sync Android directories like the SD-card content or a specific folder to a remote server ?

Thanks for rcloneExplorer, it rocks ! :+1: 

Regards

**Comment by Sergi0O** [comment]
This would be an excellent alternative for replacing rclone through termux

**Comment by FoxP** [comment]
Or maybe should you add a terminal to rcloneExplorer to interact with the built-in rclone?

**Comment by kaczmarkiewiczp** [comment]
@FoxP 
There are already great apps for accessing rclone through terminal, like [termux](https://github.com/ncw/rclone/wiki/rclone-on-Android-with-Termux). I made this app to provide GUI for rclone on Android, and I do not intend on adding terminal interface. However sync will be available soon.

**Comment by kaczmarkiewiczp** [comment]
Added sync in #193. The feature will be available in the next stable release, and is already available in the current [beta release](https://github.com/kaczmarkiewiczp/rcloneExplorer/releases/tag/1.6.0-016-22156fb-%CE%B2)

**Comment by wingsuit** [comment]
Hey thanks for your great work on this app. 

Any plans in the future to add the ability to save a folder pair so that we can run the same rclone command more easily / set it up on an automatic schedule?
