### ISSUE TITLE
Connection to AWS servers

### ISSUE THREAD

**Issue by gmag11** [kaczmarkiewiczp/rcloneExplorer#183]
Information managed by this app may be sensible. I've checked that rcloneExplorer connects to AWS servers even with no remote configured. What are those connections used for?
![NetMonitor App](https://image.ibb.co/diF7pT/ndice.jpg)

**Comment by kaczmarkiewiczp** [comment]
The app uses two different Google services, Firebase cloud messaging and Firebase crashlytics. Cloud messaging is used to push notifications when new app release is available on GitHub. Crashlytics is used for anonymous crash reporting. Unfortunately Google sends some extra information, like device model, OS number, app number, and country/city. I didn't find a away to disable those and just have crash reporting. However all the information is anonymous. Both cloud messaging and crash reporting can be disabled from settings.

After a bit of testing, I can see that all the requests to AWS seem be part of Firebase crashlytics. After disabling crash reporting in the settings there were no more connections. Could you confirm that disabling crash reporting gets rid of those connections?

**Comment by gmag11** [comment]
You're right. After disabling crash reporting I can confirm that no additional connection is made. Thank so much.
