### ISSUE TITLE
End "HTTP serve" streaming service

### ISSUE THREAD

**Issue by FoxP** [kaczmarkiewiczp/rcloneExplorer#186]
Hello,

Is there a way to end the "HTTP serve" streaming service without having to kill rcloneExplorer with an advanced (root) task manager ?

![screenshot_20180729-122450](https://user-images.githubusercontent.com/16615901/43365269-a3b9f9e2-932a-11e8-962b-432b29d2daaa.png)

**Comment by kaczmarkiewiczp** [comment]
When you HTTP serve it creates a notification (the HTTP icon). You can then expand the notification to reveal the cancel button.
![screenshot_20180729-220754 2](https://user-images.githubusercontent.com/16674420/43377184-934a1f54-937c-11e8-822f-5eec295f2675.png)
