### ISSUE TITLE
Play video from encrypted remote

### ISSUE THREAD

**Issue by FoxP** [kaczmarkiewiczp/rcloneExplorer#187]
Hello,

Is there a way to play a video from an encrypted remote ?
I'm trying to play a .mp4 file directly from a pCloud encrypted remote with:
  
- [VLC for Android](https://play.google.com/store/apps/details?id=org.videolan.vlc&hl=fr)
  
![screenshot_20180729-123342](https://user-images.githubusercontent.com/16615901/43365340-d5d61ebe-932b-11e8-81b5-a2868116f10b.png)
  
- Google Video Player (default Android video player)
  
![screenshot_20180729-123256](https://user-images.githubusercontent.com/16615901/43365341-d7798f9e-932b-11e8-8476-41ebee66a7d8.png)
  
I have also tried the "open as" "video" feature. Same issue.
The "open as" "image" works perfectly.
When i download the video manually, these two players can play it perfectly.
I have a Xiaomi Redmi Note 3 Pro Prime with LineageOS 13 Official Stable build (Android 6.0.1_r81 with security patch level 2018-06-05).

**Comment by kaczmarkiewiczp** [comment]
I can replicate this bug. Two things I've noticed: MX Player (available on the Play store) is able to open videos. I'm assuming that there are other media players that can also stream without any errors.
If I stream a video with VLC, it will show an error and quit. If then I try to stream the same video again, VLC will play it. 
This is only a termopary workaround while I try to determine why streaming doesn't work with certain media players.

**Comment by FoxP** [comment]
Maybe the default buffer / cache size is not large enough?

**Comment by kaczmarkiewiczp** [comment]
The problem seemed to be caused by spaces in filenames. I fixed this in #191.
The fix will be available in the next stable release, and current [beta release](https://github.com/kaczmarkiewiczp/rcloneExplorer/releases/tag/1.6.0-013-47533d4-%CE%B2).

**Comment by FoxP** [comment]
I tried the beta release, you fixed it. :+1:
