### ISSUE TITLE
Feature Request: Add password protection for rclone serve webdav

### ISSUE THREAD

**Issue by xiaolei0125** [kaczmarkiewiczp/rcloneExplorer#216]
@kaczmarkiewiczp ,  `rclone serve webdav ` is a very useful feature in rcloneExploer,  it will always run as a service on my phone, and I'm worried that other people on the LAN will also be able to access it.

So is there a way to add a password protection for webdav? For example, put the password settings in the app settings, thanks.

**Comment by kaczmarkiewiczp** [comment]
I tested this, and it seems that devices on the same network are able to access served files, as long as they have the IP address and port. After looking at the documentation for `rclone serve` it seems that I used a wrong flag. Since this is a security issue, I will try to have a fix as soon as possible.

**Comment by xiaolei0125** [comment]
@kaczmarkiewiczp  
Do you mean to ban access from the LAN?
But sometimes I still want to access webdav from other devices in same network, such as computer or kodi.

**Comment by kaczmarkiewiczp** [comment]
Reading my response I can see how it can come across as me removing external access. I don't plan to remove any features, sorry for the confusion. The serve dialog is getting revamped, with option to specify external access, and optional authentication.

**Comment by kaczmarkiewiczp** [comment]
This is now addressed in #217. External access is off by default now, with option to enable it, and there's also option to specify username and password for authentication. All of that is present in the same Serve dialog.

It's part of the current [beta release](https://github.com/kaczmarkiewiczp/rcloneExplorer/releases/tag/v1.7.3-beta2) and will be included in future stable release.
