### ISSUE TITLE
Request: release new rcloneExploer version for rclone v1.44

### ISSUE THREAD

**Issue by xiaolei0125** [kaczmarkiewiczp/rcloneExplorer#220]
@kaczmarkiewiczp
 Can you help to release a new version of rcloneExploer for rclone v1.44,  since rclone v1.44 has some import features and bug fix,  Thank you.

**Comment by kaczmarkiewiczp** [comment]
Sorry, I was a bit busy with personal stuff lately and didn't have as much time to work on this project as I would like :disappointed: 

I'll have a version with v1.44 in 24 hours or less.
