### ISSUE TITLE
Request: ability to set individual primary colors per rclone drive/mount/etc

### ISSUE THREAD

**Issue by moarbytes** [kaczmarkiewiczp/rcloneExplorer#226]
Having different primary colors per account/mount/whatever would be helpful for people like myself who are always tapping the wrong one. Accidentally filled up my personal drive with work junk twice in the last couple of weeks. D'oh.  

Small price to pay for such a handy app though. Thanks so much!

**Comment by patrykcoding** [comment]
That sounds like a great idea. I will look into implementing this....hopefully this weekend :crossed_fingers:
