### ISSUE TITLE
Mega remotes

### ISSUE THREAD

**Issue by caspertone2003** [kaczmarkiewiczp/rcloneExplorer#233]
@kaczmarkiewiczp 
Does 1.7.4 allow to configure a mega remote?
If yes, how?
Thanks

**Comment by buywetwok** [comment]
Only the remotes listed here can be created from the app: 
https://github.com/kaczmarkiewiczp/rcloneExplorer/tree/master/app/src/main/java/ca/pkay/rcloneexplorer/RemoteConfig

As a workaround, you can configure rclone on your computer to use the MEGA remote, copy the rclone config file from your computer to your phone, then import the config file into this app.

**Comment by caspertone2003** [comment]
TKs
