### ISSUE TITLE
Mount a remote disk into the file system 

### ISSUE THREAD

**Issue by IIeTp** [kaczmarkiewiczp/rcloneExplorer#262]
This function is useful if you are using devices similar to Nvidia Shield with a Plex server (or another android-based player with its own library cataloger). In this case, you can add the remote folder directly to Plex and watch online through it. Rclone can do this.

**Comment by x0b** [comment]
Unfortunately, mounting won't be available in rcloneExplorer because it would require root. 
For root users, there is https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone.
