### ISSUE TITLE
Suddenly started asking for password 

### ISSUE THREAD

**Issue by turkeyphant** [kaczmarkiewiczp/rcloneExplorer#273]
My rclone config password doesn't work
Nor do any passwords I can think of.

What is this password? When would I have set it? Why is it suddenly asking me only now?

**Comment by ElusiveZatchmo** [comment]
I just want to add that this is happening to me too. It started happening after my phone update to Android 10. It was working fine before the update, but now, with no setting changes, it's asking for a password out of no where.

**Comment by turkeyphant** [comment]
> I just want to add that this is happening to me too. It started happening after my phone update to Android 10. It was working fine before the update, but now, with no setting changes, it's asking for a password out of no where.

It seems this repo is abandoned. I don't why the issue cropped up but there's a maintained fork at https://github.com/x0b/rcx/blob/master/README.md that works perfectly for me now.
